modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Trikzon/Sneak-Through-Berries/issues"

[[mods]]
modId="sneakthroughberries"
version="${file.jarVersion}"
displayName="Sneak Through Berries"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/sneakthroughberries"
#logoFile=""
#credits=""
authors="Trikzon"
description='''
Lets you sneak through Sweet Berry Bushes without taking damage
'''

[[dependencies.sneakthroughberries]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"